import "server-only";
import * as OTPAuth from "otpauth";
import { ApiError } from "../client";

/**
 * In-memory, per-user TOTP (authenticator-app) enrollment state —
 * globalThis-pinned so Next dev/Turbopack module re-evaluation doesn't wipe
 * it (same idiom as auth-store.ts). Unlike the old "MFA preference" model
 * this replaced (a fabricated None/Email/Authenticator radio that didn't
 * correspond to any real capability), this is a genuinely working TOTP
 * implementation — a real secret, a real otpauth:// URI a real authenticator
 * app can scan, and real code validation — using the same shape the live
 * backend's StartTotpEnrollment/ConfirmTotpEnrollment/RemoveTotp endpoints
 * return, so mock mode is a faithful stand-in, not a placeholder. Email-OTP
 * isn't modeled here (or live — see lib/api/auth.ts's loginStartOtpEmail):
 * it's a Zitadel-side factor with no enrollment endpoint this app calls.
 */

interface MockTotpState {
  enabled: boolean;
  /** Confirmed, active secret — set once ConfirmTotpEnrollment succeeds. */
  secret: string | null;
  /** Generated by StartTotpEnrollment, discarded on confirm/on a fresh start. */
  pendingSecret: string | null;
}

const globalForSecurity = globalThis as unknown as { __vitalinkTotpState?: Map<string, MockTotpState> };
const totpByUserId = globalForSecurity.__vitalinkTotpState ?? new Map<string, MockTotpState>();
globalForSecurity.__vitalinkTotpState = totpByUserId;

function getState(userId: string): MockTotpState {
  let state = totpByUserId.get(userId);
  if (!state) {
    state = { enabled: false, secret: null, pendingSecret: null };
    totpByUserId.set(userId, state);
  }
  return state;
}

function totpFor(secret: string, label: string): OTPAuth.TOTP {
  return new OTPAuth.TOTP({
    issuer: "Vitalink",
    label,
    algorithm: "SHA1",
    digits: 6,
    period: 30,
    secret: OTPAuth.Secret.fromBase32(secret),
  });
}

export function isMockTotpEnabled(userId: string): boolean {
  return getState(userId).enabled;
}

export function startMockTotpEnrollment(userId: string, accountLabel: string): { uri: string; secret: string } {
  const secret = new OTPAuth.Secret({ size: 20 });
  const state = getState(userId);
  state.pendingSecret = secret.base32;
  return { uri: totpFor(secret.base32, accountLabel).toString(), secret: secret.base32 };
}

export function confirmMockTotpEnrollment(userId: string, code: string): void {
  const state = getState(userId);
  if (!state.pendingSecret) {
    throw new ApiError(400, "Start enrollment first — no pending authenticator setup for this account.");
  }
  const delta = totpFor(state.pendingSecret, userId).validate({ token: code.trim(), window: 1 });
  if (delta === null) {
    throw new ApiError(400, "That code didn't match. Check your authenticator app and try again.");
  }
  state.secret = state.pendingSecret;
  state.pendingSecret = null;
  state.enabled = true;
}

export function removeMockTotp(userId: string): void {
  const state = getState(userId);
  state.enabled = false;
  state.secret = null;
  state.pendingSecret = null;
}

/** Used by lib/api/mocks/auth-store.ts's login() to decide whether to
 * challenge for a code, and by loginTotp() to validate it — window:1 allows
 * the previous/next 30s step too, same tolerance a real authenticator app
 * user needs for clock drift. */
export function validateMockTotpCode(userId: string, code: string): boolean {
  const state = getState(userId);
  if (!state.enabled || !state.secret) return false;
  return totpFor(state.secret, userId).validate({ token: code.trim(), window: 1 }) !== null;
}
